# This is an example of FCW algorithm configuration

# Configuration of detector
detector:
  model: yolov5l6
  max_image_size: 480
  min_score: 0.3
  filter_in_frame: True
  min_area: 2000
  classes:  # List of classes to detect
    - car
    - bus
    - truck
    - bicycle
    - motorcycle
    - person
    # We can add more classes like dog, cow etc...


# Configuration of SORT tracker
tracker:
  min_hits: 2
  max_age: 4
  iou: 0.3


# Example configuration of warning
fcw:
  safety_zone: 50  # [m] consider objects in this radius
  danger_zone: [  # Polygon defining danger zone around the vehicle [(x,y), ...]
    [ 0, 1],
    [10, 1],
    [10,-1],
    [ 0,-1]
  ]
  prediction_length: 1  # [s] path prediction time
  prediction_step: 0.2  # [s] integration step for prediction