# This is an example of FCW algorithm configuration

# Configuration of detector
detector:
  model: yolov5m6
  max_image_size: 1000
  min_score: 0.25
  filter_in_frame: True
  min_area: 100
  classes:  # List of classes to detect
    - car
    - bus
    - truck
    - bicycle
    - motorcycle
    - person
    # We can add more classes like dog, cow etc...


# Configuration of SORT tracker
tracker:
  min_hits: 2
  max_age: 4
  iou: 0.3


# Example configuration of warning
fcw:
  safety_radius: 50  # [m] consider objects in this radius
  danger_zone:  # Polygon defining danger zone around the vehicle [(x,y), ...]
#    - [ 3, 2]
#    - [20, 2]
#    - [20,-2]
#    - [ 3,-2]
    - [ 3, 1.5]
    - [10, 1.5]
    - [10,-1.5]
    - [ 3,-1.5]
  vehicle_length: 4.6
  vehicle_width: 1.8
  vehicle_zone_buffer: 0.5
  prediction_length: 1.0  # [s] path prediction time
  prediction_step: 0.1  # [s] integration step for prediction